[package]
name = "specbmc"
version = "0.1.0"
authors = ["Emmanuel Pescosta <emmanuelpescosta099@gmail.com>"]
description = "Bounded model checker for speculative non-interference."
license = "Apache-2.0"
edition = "2018"
repository = "https://github.com/emmanuel099/specbmc"
readme = "README.md"

[features]
# Build Falcon with capstone 4 support
capstone4 = ["falcon/capstone4"]

[dependencies]
clap = "2.33.0"
error-chain = "0.12"
num-bigint = "0.2"
num-traits = "0.2.1"
falcon = { git = "https://github.com/emmanuel099/falcon" }
falcon_muasm = { git = "https://github.com/emmanuel099/falcon-muasm" }
rsmt2 = "0.10.0"
bit-vec = "0.6.1"
