name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1

      - name: Install capstone 4
        run: |
          echo 'deb http://ftp.de.debian.org/debian bullseye main' | sudo tee -a /etc/apt/sources.list &&
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 04EE7237B7D453EC &&
          sudo apt update &&
          sudo apt install -t bullseye -y libcapstone-dev

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose

      - name: Run clippy
        run: cargo clippy --all -- -D warnings

      - name: Install Yices
        env:
          YICES2_ARTIFACT_URL: ${{ secrets.YICES2_ARTIFACT_URL }}
        run: |
          curl -L -o yices "$YICES2_ARTIFACT_URL" &&
          chmod +x yices &&
          sudo mv yices /usr/bin/

      - name: Install CVC4
        run: sudo apt install -y cvc4

      - name: Install Z3
        run: sudo apt install -y z3

      - name: Run system tests
        run: python3 test.py
