name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install capstone 4
        run: |
          echo 'deb http://mirrors.kernel.org/ubuntu hirsute main universe' | sudo tee -a /etc/apt/sources.list &&
          sudo apt update &&
          sudo apt install -t hirsute -y libcapstone-dev

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose

      - name: Run clippy
        run: cargo clippy -- -D warnings

      - name: Install Yices
        env:
          YICES2_ARTIFACT_URL: ${{ secrets.YICES2_ARTIFACT_URL }}
        run: |
          curl -L -o yices "$YICES2_ARTIFACT_URL" &&
          chmod +x yices &&
          sudo mv yices /usr/bin/

      - name: Install CVC4
        run: sudo apt install -t hirsute -y cvc4

      - name: Install Z3
        run: sudo apt install -t hirsute -y z3

      - name: Run system tests
        run: TIMEOUT=120 python3 test.py
