name: Rust

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1

      - name: Install capstone 4
        run: |
          echo 'deb http://ftp.de.debian.org/debian experimental main' | sudo tee -a /etc/apt/sources.list &&
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 04EE7237B7D453EC &&
          sudo apt update &&
          sudo apt install -t experimental -y libcapstone-dev

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose

      #- name: Run clippy
      #  run: cargo clippy --all-targets -- -D warnings -W clippy::pedantic

      - name: Install Yices
        env:
          YICES2_ARTIFACT_URL: ${{ secrets.YICES2_ARTIFACT_URL }}
        run: |
          curl -L -o yices "$YICES2_ARTIFACT_URL" &&
          chmod +x yices &&
          sudo mv yices /usr/bin/

      - name: Run system tests
        env:
          SOLVER: yices2
        run: python3 test.py
