name: Rust

on:
    push:
      branches:
        - master
    pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install capstone
      run: sudo apt install -y libcapstone-dev
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run clippy
      run: cargo clippy --all-targets -- -D warnings -W clippy::pedantic
